name: Run Tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Run mypy
        run: mypy src/*.py tests/*.py

      - name: Run tests
        run: pytest -v
